/* content/chains.js for Module 1, PORTED from the estate's Module 1 guide.
   Module 2's warm-up chains were written for hs2-test2 from her Test 2 "diagrams &
   processes" post. Module 1 has no such post ("There is no such list" — her own
   answer to "what will be in Test 1"), but the estate already carries Module 1's
   mechanisms as chains: hs2-module1-guide/index.html (the Ten Engines guide) holds
   every one as a `.chainbox` of beads and arrow verbs, each inside an engine section
   that names the criteria it serves. This script lifts them verbatim — same bead
   text, same verbs, same order — into the {id, sys, name, src, beads:[{t}|{v}]}
   shape template.html already renders. Nothing is written by hand here; re-run
   after the guide changes. Chains with fewer than four beads cannot be blanked
   sensibly and are skipped (build.mjs would reject them anyway). */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const GUIDE = process.env.HS2_GUIDE || path.join(HERE, '..', 'hs2-module1-guide', 'index.html');
const OUT = path.join(HERE, 'content', 'chains.js');

const html = fs.readFileSync(GUIDE, 'utf8');
const un = (s) => s
  .replace(/&rarr;/g, '→').replace(/&mdash;/g, '—').replace(/&ndash;/g, '–').replace(/&times;/g, '×').replace(/&minus;/g, '−')
  .replace(/&middot;/g, '·').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&#39;|&rsquo;/g, '’').replace(/&lsquo;/g, '‘').replace(/&ldquo;/g, '“').replace(/&rdquo;/g, '”').replace(/&quot;/g, '"')
  .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(+d))
  .replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

/* engine sections: id, chip (system label), criteria line, title */
const engines = [...html.matchAll(/<section id="(e\d+)" class="engine[^"]*">([\s\S]*?)<\/section>/g)].map(m => ({
  id: m[1], html: m[2],
  title: un((m[2].match(/<h2>([\s\S]*?)<\/h2>/) || [])[1] || ''),
  crit: un((m[2].match(/<span class="crit">([\s\S]*?)<\/span>/) || [])[1] || ''),
}));
if (engines.length !== 10) { console.error(`✗ expected the ten engines, found ${engines.length}`); process.exit(1); }
/* the guide's own order: e1–e6 cardiovascular, e7–e9 respiratory, e10 lymphatic */
const SYS = (eid) => { const n = +eid.slice(1); return n <= 6 ? 'cvs' : n <= 9 ? 'resp' : 'lymph'; };

const chains = [], skipped = [];
for (const eng of engines) {
  for (const box of eng.html.matchAll(/<div class="chainbox"[^>]*data-chain="([^"]+)"[^>]*data-name="([^"]+)"[^>]*>([\s\S]*?)<\/div>\s*<\/div>/g)) {
    const [, id, name, inner] = box;
    const beads = [...inner.matchAll(/<span class="bead[^"]*">([\s\S]*?)<\/span>|<span class="arrow"[^>]*data-v="([^"]*)"/g)]
      .map(m => m[1] != null ? { t: un(m[1]) } : { v: un(m[2]) })
      .filter(b => (b.t ?? b.v).length);
    const nT = beads.filter(b => b.t).length;
    if (nT < 4) { skipped.push(`${id} (${nT} beads)`); continue; }
    chains.push({ id, sys: SYS(eng.id), name: un(name), src: `Module 1 guide · ${eng.title} (${eng.crit})`, beads });
  }
}
if (!chains.length) { console.error('✗ no chains found'); process.exit(1); }

const body = chains.map(c =>
  `  {\n    id: ${JSON.stringify(c.id)}, sys: '${c.sys}', name: ${JSON.stringify(c.name)},\n    src: ${JSON.stringify(c.src)},\n    beads: [\n` +
  c.beads.map(b => `      ${JSON.stringify(b)},`).join('\n') + `\n    ],\n  },`).join('\n');
fs.writeFileSync(OUT, `/* Warm-up chains — GENERATED by port-chains.mjs from hs2-module1-guide/index.html
   (the estate's Ten Engines guide for this module); do not edit here. Each chain is
   the guide's own bead/verb sequence, verbatim, and names the engine and criteria it
   sits under there. Like Module 2's, these are scaffolds built from her material,
   not her material — the warm-up says so on screen. */
export const CHAINS = [
${body}
];
`);
const by = {}; for (const c of chains) by[c.sys] = (by[c.sys] || 0) + 1;
console.log(`wrote ${OUT}: ${chains.length} chains ${JSON.stringify(by)} from ${engines.length} engines` + (skipped.length ? `; skipped (too short): ${skipped.join(', ')}` : ''));
