/* focus.js — Module 1: what to learn, and how far.
 *
 * WHERE THE ROWS COME FROM. Every row is one of HER numbered assessment criteria — "Continuous Tests and Exam Focus Points"
 * (Science 2 Detailed Content.docx), Module 1: Cardiovascular 1-15 (criterion 5 in its three parts 5.1-5.3), Respiratory 1-17,
 * Lymphatic 1-4 — the same list as her Canvas page "Module 1: Learning checklist", of which she said: "There is no such list [of
 * test questions]. The closest to such a list is the assessment criteria … it limits what I may ask." Two rows are the other way
 * round and say so: 'exam-cases' (her board, not a criterion) and 'fluid-balance' (her Module 1.3 quiz asks it, her criteria
 * never name it). Rows her criteria name but her quizzes never ask are kept with 0 questions: that is triage information too.
 *
 * WHERE THE NUMBERS COME FROM. The build counts them — never a person. content/topics.js puts every shipped question on exactly
 * one row (rules, then every group read by eye, then 123 moved by hand); build.mjs fills in n, all, pts, qz, saq per row and the
 * TIER from pts (1: 30+ marks · 2: 12-29 · 3: under 12). The exam-cases row counts her three case packs (content/cases.js).
 *
 * TIER 0 = SHE SAID SO, in her own words. This sim now serves the FINAL (Thu 5 Nov 2026), and her own words about the final are
 * that it "is based on all the *starred case studies" — Module 1's are cases 2, 3 and 4. When she posts exam pointers (the exam
 * case-study helpline opens Mon 19 Oct), whatever she names moves up here. Nothing is in tier 0 on my say-so.
 *
 * `done` = what you must be able to DO to tick it.  `ask` = the shape she actually uses.  `cap` = where her bank stops.
 * done / ask / cap are MY reading of her questions (21 Sep 2026) — the questions under each row are hers.
 */
export const FOCUS = [
/* ══════════ THE EXAM'S OWN SIGNAL ══════════ */
{ id:'exam-cases', sys:'mixed', tier:0, crit:'Her exam-cases board (starred cases 2, 3, 4)', t:'Exam cases 2, 3 and 4: lymph-node removal, asthma, panic attack',
  done:'Answer every question of the three starred Module 1 cases from memory. Case 2 (Mary): the lymphatic system’s three jobs, the axillary nodes’ role in the spread of cancer, and why her arm swells once they are gone (fluid dynamics). Case 3 (Ane, asthma): the term for difficult breathing, what narrows in her airways and what that does to resistance and ventilation, what the inhaler does, the ways dust is kept out of the lungs, the mucociliary escalator and what smoking does to it, and how her blood pressure comes back down after fight-or-flight. Case 4 (Manaia, panic attack): the steps of inhalation and of exhalation, the muscles of forced breathing, what makes ventilation easier or harder, normal blood pH, the bicarbonate buffer equation, and how breathing rate and depth change blood pH and respond to it.',
  ask:'Scenario first, then 3 to 8 short questions worth 1-4 marks each, several asking you to bullet-point the steps. Her model answers are one marking point per line; the full mock test deals one case question per sitting, rotating through all of them.',
  cap:'Her day-1 post: the on-campus exam “is based on all the *starred case studies”. These three are Module 1’s. The answers in this tool are HER model answers from her 2024 case-study deck.' },

/* ══════════ CARDIOVASCULAR ══════════ */
{ id:'cvs-function', sys:'cvs', crit:'Cardiovascular 1 · “Describe the function of cardiovascular system”', t:'What the cardiovascular system is for',
  done:'Say in one line each: the heart pumps, arteries carry away, veins return, capillaries exchange — and that the human system is closed and double (pulmonary + systemic).',
  ask:'One-liners: “What kind of blood system do humans have?”, “Blood is returned to the heart via the…”.',
  cap:'Barely asked on its own: the substance sits in the vessel, circuit and heart rows.' },
{ id:'cvs-vessels', sys:'cvs', crit:'Cardiovascular 2 · “Describe the structural and functional differences between the artery, vein and capillary”', t:'Arteries, veins and capillaries: how their walls differ and why',
  done:'Draw or describe an artery beside a vein: thick tunica media and internal elastic lamina vs thin walls and valves; round vs collapsed lumen. Name the three capillary types and where each lives (continuous — brain, fenestrated — kidney, sinusoidal — marrow/liver). Explain why you feel a pulse in an artery but not a vein, and that most blood sits in the veins.',
  ask:'Label-the-micrograph matches (tunica media, valve, internal elastic lamina), “which layer causes vasoconstriction?”, a structure table as drop-downs, and two short essays: draw both vessels, and why no pulse in a vein.',
  cap:'Wall layers, valves, capillary types, pulse. No histology beyond what her two micrographs show.' },
{ id:'cvs-capillary-fluid', sys:'cvs', crit:'Cardiovascular 3 · “Outline the factors involved in capillary fluid movement – including hydrostatic and oncotic pressures”', t:'Capillary fluid movement: hydrostatic vs oncotic pressure',
  done:'Explain the two forces across a capillary: hydrostatic pressure pushes fluid OUT at the arterial end, oncotic (colloid osmotic) pressure from plasma proteins pulls it back at the venous end. Use that to explain oedema in hypertension (more push), low albumin / kwashiorkor (less pull), and dehydration.',
  ask:'Short essays with a named cause (“hypertension and edema”, “kwashiorkor’s distended abdomen”) and “find the errors” match tables where two words in her answer are wrong.',
  cap:'Two forces, three causes of oedema. No numbers for net filtration pressure are asked.' },
{ id:'cvs-flow-physics', sys:'cvs', crit:'Cardiovascular 4 · “Describe the relationship between blood pressure, blood flow, and peripheral resistance, and velocity of blood flow”', t:'Blood pressure, flow, resistance and velocity',
  done:'State BP = CO × PR (SVR) and use it: vessel diameter up → resistance down → BP down; vasoconstriction does the reverse. Explain why pressure falls from arteries → arterioles → capillaries → venae cavae.',
  ask:'One-mark formula and prediction MCQs (“predict the change in PR as diameter increases”), a T/F on vasoconstriction, and one 3-mark essay on mean pressure along the tree.',
  cap:'Qualitative only: no Poiseuille, no calculations beyond BP = CO × PR.' },
{ id:'cvs-heart-location', sys:'cvs', crit:'Cardiovascular 5.1 · “Describe the functional anatomy of the heart and the major blood vessels of the heart. Be able to describe: Location and orientation of the heart”', t:'Where the heart sits and which way it points',
  done:'Place the heart in the mediastinum, apex down and to the left (5th intercostal space), base up behind the sternum.',
  ask:'Not asked in any of her Module 1 quizzes.',
  cap:'On her criteria list, in none of her quizzes: know the one sentence and move on.' },
{ id:'cvs-heart-coverings', sys:'cvs', crit:'Cardiovascular 5.2 · “Describe the functional anatomy of the heart and the major blood vessels of the heart. Be able to describe: The coverings of the heart”', t:'The heart’s coverings: pericardium and epicardium',
  done:'Name the layers from outside in — fibrous pericardium, parietal serous pericardium, pericardial cavity with its fluid, visceral pericardium = epicardium — and say what each does. Explain cardiac tamponade as fluid in that cavity squeezing the heart.',
  ask:'Photo and diagram identification (“what is held by the forceps?”), “what is the difference between visceral and parietal / pericardium, epicardium and endocardium?” essays, and T/Fs that swap the names of the space.',
  cap:'Layer names and jobs, tamponade. Her trap: the space is the pericardial cavity, not an “epicardial space”.' },
{ id:'cvs-heart-walls', sys:'cvs', crit:'Cardiovascular 5.3 · “Describe the functional anatomy of the heart and the major blood vessels of the heart. Be able to describe: The structure and function of the heart walls, chambers and valves”', t:'Heart walls, chambers and valves',
  done:'Label a heart diagram cold: four chambers, septa, the four valves by name and position, chordae tendineae on papillary muscles, trabeculae and pectinate muscles. Say which layer is thickest (myocardium), which lines the chambers and forms the valves (endocardium), why the left ventricle is thicker, and what stenosis or regurgitation of a valve does.',
  ask:'Her most-asked row: numbered-diagram matches (the same heart image several times), one-line MCQs from her CVS2 wordlist, “difference between tricuspid and mitral / semilunar and AV” essays, valve-disease MCQs.',
  cap:'Anatomy and the job of each part. Fetal remnants (fossa ovalis) appear only as labels.' },
{ id:'cvs-circuits', sys:'cvs', crit:'Cardiovascular 6 · “Describe the blood flow through the heart, systemic circuit, pulmonary circuit, and coronary circulation”', t:'Blood flow through the heart, the two circuits and the coronaries',
  done:'Trace blood from the venae cavae through every chamber and valve to the aorta, and compare the pulmonary circuit (low pressure, to the lungs) with the systemic. Name the coronary arteries and their branches (LAD = the widow maker, circumflex, marginal, posterior interventricular), the coronary sinus, and the big named vessels: aortic arch branches, vessels of the neck and limbs, the veins into the IVC, the hepatic portal vein.',
  ask:'Order-the-sequence questions, “name four arteries/veins and what they supply” essays (asked twice each), coronary MCQs, a labelled neck diagram, and three questions on how blood flow changes at birth.',
  cap:'Named vessels are asked by name and territory only. Fetal circulation is in her quizzes but not in her criteria.' },
{ id:'cvs-sounds', sys:'cvs', crit:'Cardiovascular 7 · “Describe the sounds the heat makes and the best places where the sounds can be detected”', t:'Heart sounds and murmurs',
  done:'Say which closure makes LUB (the AV valves, start of systole) and which makes DUB (the semilunar valves), and what a murmur is (turbulent flow through a leaky or narrowed valve).',
  ask:'Short essays in her marks-per-line style and the phonocardiogram MCQs on her cardiac-cycle figure.',
  cap:'Lub, dub, murmur. Where to place the stethoscope is in her criteria but not asked in her quizzes.' },
{ id:'cvs-conduction', sys:'cvs', crit:'Cardiovascular 8 · “Describe the generation and conduction of the basic rhythm of heart in relation to cardiac cycle and electrocardiogram”', t:'The conduction system, the cardiac cycle and the ECG',
  done:'Order the conduction system (SA node → AV node → bundle of His → bundle branches → Purkinje fibres) and label it; say what P, QRS and T represent (atrial depolarisation, ventricular depolarisation, ventricular repolarisation) and label an ECG trace. Explain automaticity and the refractory period, and what an ECG can and cannot show (electrical changes only — not valves or blood pressure).',
  ask:'Label-the-ECG and label-the-conduction-system matches (each asked twice), “find the error” answers, ECG-in-a-case clozes (Lagi), and two lab essays on abnormalities an ECG detects.',
  cap:'Waves and components, not interpretation of real strips beyond “normal” vs “shock”.' },
{ id:'cvs-co-control', sys:'cvs', crit:'Cardiovascular 9 · “Discuss the homeostatic mechanisms involved in the control of heart rate, stroke volume and cardiac output (both neural and hormonal control)”', t:'Control of heart rate, stroke volume and cardiac output',
  done:'Know CO = HR × SV and the resting numbers (about 70 bpm × 70 mL ≈ 5 L/min). Predict what happens to SV with more preload, more contractility (adrenaline) and more afterload (hypertension); define cardiac reserve and ejection fraction; say how sympathetic and parasympathetic (vagus) nerves and adrenaline change the rate.',
  ask:'Paired predict-the-change MCQs (increase / decrease), a normal-values match, and a 20-blank cloze on neural and hormonal control of heart rate.',
  cap:'Direction of change, not numbers beyond the resting values.' },
{ id:'cvs-co-factors', sys:'cvs', crit:'Cardiovascular 10 · “Explain the effect of general factors on heart rate, stroke volume and cardiac output”', t:'General factors that change heart rate, stroke volume and cardiac output',
  done:'Explain why a trained athlete’s resting rate is lower and how heart rate changes between lying, sitting, standing and exercising (the lab readings).',
  ask:'One T/F and her two lab essays: “discuss the heart rate changes during the different ECG readings and why”.',
  cap:'Posture, fitness and exercise as in her lab. Age and temperature are not asked.' },
{ id:'cvs-cardiac-factors', sys:'cvs', crit:'Cardiovascular 11 · “Describe the effect of venous return, plasma electrolytes, stress and exercise on cardiac functions”', t:'Venous return, electrolytes, stress and exercise on the heart',
  done:'Explain Starling’s law in words — more venous return stretches the ventricle and raises stroke volume — and how exercise raises venous return (muscle and respiratory pumps).',
  ask:'Predict-the-change MCQs and one 10-blank cloze that runs through venous return, electrolytes, stress and exercise.',
  cap:'Venous return carries it; electrolytes appear only inside that one cloze.' },
{ id:'cvs-bp-control', sys:'cvs', crit:'Cardiovascular 12 · “Discuss the short-term and long-term homeostatic control of blood pressure and the effect of general factors on blood pressure (include baroreceptors, vasomotor centre, cardiac centre, reflex control; renal and hormonal control including adrenaline and renin-angiotensin-aldosterone etc)”', t:'Short- and long-term control of blood pressure',
  done:'Run the baroreceptor reflex (carotid sinus and aortic arch → cardiac and vasomotor centres in the medulla → heart rate and vessel diameter) in the right order, and the renin-angiotensin-aldosterone chain (JG cells → renin → angiotensin I → ACE → angiotensin II → aldosterone and ADH → volume and BP), including what ACE inhibitors block.',
  ask:'Order-the-steps matches (baroreflex on standing up; RAAS), “find the two errors” answers, T/Fs that swap baroreceptors and chemoreceptors, and a 5-mark essay on RAAS and ACE inhibitors.',
  cap:'Her traps: the aortic and carotid BODIES are chemoreceptors (the sinus and arch are baroreceptors); ACE inhibitors LOWER blood pressure.' },
{ id:'cvs-bp-stress', sys:'cvs', crit:'Cardiovascular 13 · “Describe how blood pressure can be affected by stress, exercise etc”', t:'How stress and exercise change blood pressure',
  done:'Explain why blood pressure rises during exercise and stress (sympathetic drive, more cardiac output, redistributed flow) and why that serves perfusion.',
  ask:'One case cloze (Oliana exercising).',
  cap:'One question in her bank.' },
{ id:'cvs-shock', sys:'cvs', crit:'Cardiovascular 14 · “Define circulatory shock; briefly describe the types and the signs and events of hypovolemic shock”', t:'Circulatory shock',
  done:'Define shock as inadequate tissue perfusion, name the types (hypovolaemic, cardiogenic, obstructive, distributive: septic, anaphylactic, neurogenic) with a cause of each, and explain the compensation in hypovolaemic shock (cold clammy skin, tachycardia, fast breathing = sympathetic response).',
  ask:'Scenario MCQs (“a trauma patient…”, “a C5 transection…”, “the ECG shows…”: which shock?), select-all lists, and one short case essay.',
  cap:'Types, causes and the compensation signs. No treatment protocols.' },
{ id:'cvs-terms', sys:'cvs', crit:'Cardiovascular 15 · “Explain related terms and/or homeostatic imbalances such as: Pulse, Cardiac Output, Blood Pressure, Blood Flow, Peripheral Resistance, Tissue Perfusion, Vasoconstriction, Vasodilation, Pressure Points, ECG, Coronary Arteries, Coronary Circulation, Heart Attack, Myocardial Infarction, Ischaemia, Myocardium, Atrial Systole, Atrial Diastole, Ventricular Systole, Ventricular Diastole, Pericarditis, Myocarditis, Endocarditis, Angina Pectoris, Myocardial Infarction, Asystole, Bradycardia, Tachycardia, Positive And Negative Inotropic Action, Positive And Negative Chronotropic Action, Congestive Heart Failure, Ventricular Fibrillation, Hypertension, Hypotension”', t:'The cardiovascular terms on her list',
  done:'Define on sight every term in her criterion 15: pulse, cardiac output, blood pressure (systolic, diastolic, pulse pressure), peripheral resistance, perfusion, vasoconstriction/dilation, ischaemia, infarction, angina, heart failure, brady-/tachycardia, the -itis conditions, inotropic and chronotropic.',
  ask:'Heavy: her CVS2 “fill in the correct terms” exercise is 25 blanks on its own, plus definition matches with deliberate errors to find.',
  cap:'Definitions. The terms reappear inside the other rows’ questions.' },

/* ══════════ RESPIRATORY ══════════ */
{ id:'resp-function', sys:'resp', crit:'Respiratory 1 · “Explain the function of the respiratory system and the processes of respiration pulmonary ventilation, external and internal respiration, transport of blood gases, cellular respiration”', t:'What respiration is for, and its four processes',
  done:'Name the four processes — pulmonary ventilation, external respiration, transport of gases, internal respiration — and say why it happens at all (O2 for ATP, CO2 out).',
  ask:'One MCQ in her bank.',
  cap:'The processes each have their own row below.' },
{ id:'resp-anatomy', sys:'resp', crit:'Respiratory 2 · “Describe the functional anatomy of the organs of the respiratory system location, structure and function of the nose and paranasal sinuses, the pharynx, larynx, trachea, the bronchial tree, the lungs and pleural membranes.”', t:'The organs of the respiratory tract, from nose to pleura',
  done:'Label the tract on her diagrams and her lab photos: nasal cavity, pharynx, larynx, trachea (C-shaped cartilage, trachealis), bronchi, bronchioles, lungs (the right is bigger), pleura (visceral on the lung, parietal on the wall, the cavity between). Match the epithelium to the tube (pseudostratified in the trachea, columnar in bronchi, cuboidal in bronchioles, squamous in alveoli).',
  ask:'Labelled figures and lab photos with one-mark questions, histology matches, and T/Fs on which parts have cartilage.',
  cap:'Names, positions and linings. Sinuses are in her criteria but not asked.' },
{ id:'resp-zones', sys:'resp', crit:'Respiratory 3 · “Differentiate between the organs of the conducting and respiratory zones and between the upper and lower respiratory tract”', t:'Conducting vs respiratory zone, upper vs lower tract',
  done:'Sort any part into the conducting zone (nose to terminal bronchioles) or the respiratory zone (respiratory bronchioles, alveolar ducts, alveoli), and say which diseases hit which (COPD the conducting zone, pneumonia the respiratory zone).',
  ask:'T/Fs that list parts and claim “only X…”, an order-the-bronchial-tree MCQ, and two case essays (COPD vs pneumonia; asthma medication).',
  cap:'The zone boundary is at the respiratory bronchiole — that is what her T/Fs test.' },
{ id:'resp-airpath', sys:'resp', crit:'Respiratory 4 · “Describe the pathway of air through the nose to the lungs in relation to the conduction of air, protective mechanisms, and production of sound”', t:'The path of air, and how the airway protects itself',
  done:'Trace air from the nostrils to the alveoli in order, and explain the mucociliary escalator (goblet cells trap, cilia sweep up), what smoking does to it, and how the epiglottis stops choking.',
  ask:'Sequence T/Fs, a lab-image “the part labelled B is the cilia”, a smoking essay and a choking case.',
  cap:'Sound production is in her criteria but not asked.' },
{ id:'resp-alveoli', sys:'resp', crit:'Respiratory 5 · “Describe the structure of the alveoli (alveoli, respiratory membrane, and surfactant in relation to protection and gaseous exchange”', t:'Alveoli, the respiratory membrane and surfactant',
  done:'Say what type I cells (thin, for diffusion) and type II cells (surfactant) do, what the respiratory membrane is made of, why surfactant keeps alveoli open, and why premature babies get respiratory distress syndrome. Explain why lung tissue floats and a still-born lung sinks.',
  ask:'One-mark MCQs and T/Fs, the IRDS/NRDS pair, and the lab-beaker questions.',
  cap:'Her trap: the respiratory membrane is NOT “alveolar cells and surfactant”.' },
{ id:'resp-volumes', sys:'resp', crit:'Respiratory 6 · “Define the lung volumes and capacities and explain their clinical significance”', t:'Lung volumes and capacities',
  done:'Read a spirometer trace: tidal, inspiratory reserve, expiratory reserve and residual volumes, and the capacities built from them (vital, inspiratory, functional residual, total). Say why residual volume matters and what age, sex and height do to capacity.',
  ask:'Label-the-trace match, one-line definitions repeated across her quizzes, and a peak-flow MCQ.',
  cap:'Definitions and the trace. No calculations.' },
{ id:'resp-ventilation', sys:'resp', crit:'Respiratory 7 · “Describe the process of pulmonary ventilation in relation to pressure and volume changes and the factors that affect pulmonary ventilation such as airway resistance, surface tension, lung compliance, negative intrapleural pressure”', t:'Pulmonary ventilation: pressure, volume and the muscles',
  done:'Explain inspiration and expiration with Boyle’s law: diaphragm and external intercostals contract, volume up, intrapulmonary pressure down, air in; quiet expiration is passive recoil, forced breathing recruits accessory muscles. Explain negative intrapleural pressure, compliance, pneumothorax and atelectasis.',
  ask:'Lots of one-mark MCQs and T/Fs (“all true of inspiration except…”), the bell-jar model, two self-mark definitions, and a punctured-rib case.',
  cap:'Mechanics in words. Gas laws are named (Boyle, Henry), not calculated.' },
{ id:'resp-air-composition', sys:'resp', crit:'Respiratory 8 · “Explain the difference in the composition of atmospheric air and alveolar air”', t:'Atmospheric vs alveolar air',
  done:'Know that nitrogen and oxygen make up about 99% of air, state Dalton’s law (each gas’s partial pressure is its share of the total), and say why alveolar air has less O2 and more CO2 and water vapour than the air outside.',
  ask:'The same two MCQs asked in several quizzes.',
  cap:'Two facts and one law.' },
{ id:'resp-external', sys:'resp', crit:'Respiratory 9 · “Describe the processes of external respiration and factors that affect gas exchange”', t:'External respiration and what affects gas exchange',
  done:'List what affects exchange in the lung (partial-pressure gradients, membrane thickness and area, ventilation-perfusion match) and explain why CO2 exchange keeps pace with O2 despite a smaller gradient (it is about 20 times more soluble).',
  ask:'“Affected by all the following EXCEPT…” and the CO2-solubility MCQ, repeated across her quizzes.',
  cap:'Qualitative only.' },
{ id:'resp-internal', sys:'resp', crit:'Respiratory 10 · “Describe the processes of internal respiration and factors that affect gas exchange”', t:'Internal respiration',
  done:'Explain exchange at the tissues: O2 moves into cells where tissue PO2 is low, CO2 moves out where it is high.',
  ask:'One MCQ in her bank.',
  cap:'One question.' },
{ id:'resp-o2-transport', sys:'resp', crit:'Respiratory 11 · “Describe the transport of oxygen in the blood according to chemical changes that occur and the factors that affect transport of blood gases”', t:'How oxygen is carried',
  done:'Say that most O2 rides on haemoglobin (four haem groups, fully saturated at four O2), what promotes unloading (heat, acid, CO2, BPG — the Bohr effect; NOT white cell count), and why carbon monoxide is dangerous.',
  ask:'Short MCQs repeated across quizzes and a haemoglobin T/F set.',
  cap:'No curve reading beyond “what shifts it”.' },
{ id:'resp-co2-transport', sys:'resp', crit:'Respiratory 12 · “Describe the transport of carbon dioxide in the blood according to chemical changes that occur and the factors that affect transport of blood carbon dioxide”', t:'How carbon dioxide is carried',
  done:'Give the three forms: mostly bicarbonate in plasma, 10-20% bound to haemoglobin (carbaminohaemoglobin), a little dissolved.',
  ask:'The same MCQ repeated across her quizzes, and one haemoglobin match.',
  cap:'The three forms and their rough shares.' },
{ id:'resp-rhythm', sys:'resp', crit:'Respiratory 13 · “Describe the generation of basic respiratory rhythm and it’s control e.g. the Medullary and pontine respiratory groups”', t:'The breathing centres and the basic rhythm',
  done:'Place the rhythm in the medulla (dorsal group for inspiration, ventral for forced breathing) and the pons, name the phrenic nerve to the diaphragm, and explain the inflation reflex (stretch receptors).',
  ask:'T/Fs that swap the dorsal and ventral groups, one-line MCQs and a case cloze.',
  cap:'Centres and nerves by name.' },
{ id:'resp-chemical', sys:'resp', crit:'Respiratory 14 · “Discuss the chemical factors that influence the rate and depth of ventilation e.g. Pco2 , pH, and Po2”', t:'Chemical control: CO2, pH and O2',
  done:'Explain that rising CO2 (and falling pH) is the main drive to breathe, sensed centrally in the medulla and peripherally in the carotid and aortic bodies; name normal blood pH (7.35-7.45); classify acidosis and alkalosis as respiratory or metabolic from a short story (over-breathing → low CO2 → respiratory alkalosis; ketones → metabolic acidosis).',
  ask:'T/Fs about the chemoreceptors, pH classification MCQs, and an 8-mark essay on hyper- and hypoventilation and blood pH.',
  cap:'Two of her acid-base keys are wrong and are held (see the held list). Blood-gas interpretation stops at naming the disturbance.' },
{ id:'resp-conscious', sys:'resp', crit:'Respiratory 15 · “Discuss the effect of emotions and conscious control on the rate and depth of breathing e.g. Hypothalamic and cortical control of breathing”', t:'Emotion and conscious control of breathing',
  done:'Say that the cortex can override the rhythm for a while (holding your breath, speaking) and the hypothalamus changes it with emotion.',
  ask:'Not asked in any of her Module 1 quizzes.',
  cap:'On her criteria list, in none of her quizzes.' },
{ id:'resp-exercise', sys:'resp', crit:'Respiratory 16 · “Discuss the effect of exercise, body temperature, pain, and irritation to air passageways on the rate and depth of ventilation”', t:'Exercise, temperature, pain and irritation',
  done:'Explain the cough reflex: particles on the carina trigger it, and the trachealis contracts to narrow the trachea and force the air out.',
  ask:'Carina and trachealis MCQs and T/Fs, repeated across her quizzes.',
  cap:'Her bank asks the cough; exercise and temperature effects on ventilation are not asked here.' },
{ id:'resp-terms', sys:'resp', crit:'Respiratory 17 · “Explain the following terms and/or homeostatic imbalances: Alveoli, Asthma, Chronic Bronchitis, Bronchodilator, Negative Pressure,Positive Pressure, Cellular Respiration, Pleural Pressure, Atmospheric Pressure At Sea Level, Partial Pressure Of Gases, Boyle’s Law, Henry’s Law, Hypoxia, Hypocapnea, Hypercapnoea, Dyspnoea, Apnoea, Asthma, Emphysema, Tuberculosis, Chronic Bronchitis, Eupnoea, Tachypnoea, Hyperventilation”', t:'The respiratory terms on her list',
  done:'Define on sight: asthma, bronchitis, emphysema, pneumonia, bronchiolitis, hypoxia, dyspnoea, apnoea, eupnoea, pneumothorax, atelectasis, bronchodilator.',
  ask:'Point-at-the-part MCQs on her tracheobronchial-tree figure, a four-term cloze, and an asthma case.',
  cap:'Definitions and where each disease sits.' },

/* ══════════ LYMPHATIC ══════════ */
{ id:'lymph-function', sys:'lymph', crit:'Lymphatic 1 · “Describe the functions of the lymphatic system e.g. immune and body defence mechanism, fluid volume, and absorption and transport of lipid”', t:'What the lymphatic system does',
  done:'Give its three jobs: return tissue fluid (fluid balance), immunity, and absorb fat from the gut (lacteals).',
  ask:'Two MCQs (its major function; which is NOT a function).',
  cap:'The same three jobs are the first question of exam case 2.' },
{ id:'lymph-anatomy', sys:'lymph', crit:'Lymphatic 2 · “Demonstrate knowledge of the functional anatomy of the components of lymphatic system - location, structure and function of lymphoid organs, lymph nodes, spleen, lymphatic capillaries and vessels”', t:'The lymphatic organs',
  done:'Say where Peyer’s patches are (distal jejunum and ileum — MALT), how the thymus differs from the other organs, and which organs are and are not lymphatic.',
  ask:'Three MCQs.',
  cap:'Lymph node structure, spleen and tonsils are in her criteria but thin in her bank.' },
{ id:'lymph-cvs', sys:'lymph', crit:'Lymphatic 3 · “Describe the relationship between the cardiovascular system and lymphatic system in relation to transport and drainage of lymph”', t:'How lymph drains back into the blood',
  done:'Explain what moves lymph (skeletal muscle and breathing pressure changes, valves) and where it rejoins the blood (subclavian veins via the thoracic and right lymphatic ducts).',
  ask:'One T/F.',
  cap:'One question; it carries exam case 2 (the swollen arm).' },
{ id:'lymph-terms', sys:'lymph', crit:'Lymphatic 4 · “Explain related terms and homeostatic imbalances of lymphatic system such as buboes, lymphoedema, lymphangitis, hodgkin’s disease, splenectomy, tonsillitis, sentinel node, swollen glands, ruptured spleen”', t:'The lymphatic terms on her list',
  done:'Match each condition to its description: lymphoedema, lymphangitis, buboes, Hodgkin’s, splenectomy, tonsillitis, sentinel node, swollen glands, and mesenteric adenitis from her case.',
  ask:'A 10-mark matching table and a 10-blank case cloze.',
  cap:'Descriptions only.' },
{ id:'fluid-balance', sys:'lymph', crit:'Not in her numbered criteria: her Module 1.3 quiz', t:'Fluid and electrolyte balance (her Module 1.3 quiz)',
  done:'Explain osmosis between plasma and red cells, name a clinical sign of dehydration, what to watch for in a patient on a loop diuretic, and which fluid replaces an intracellular deficit.',
  ask:'Nursing-style MCQs from her fluid-balance quiz.',
  cap:'Her criteria never name this; her quiz does. One of its acid-base questions is held for a wrong key.' },
];
