/* Model answers for the essay questions in her Module 1 quizzes.
   Canvas publishes no key for essays, but for Module 1 she left most of them in the
   open: a feedback comment under the question on the graded page, a marked SAQ on her
   CVS 2 learning page, a labelled image. Where an entry is HERS (`hers: true`) the steps
   are her wording split one marking point per line (spelling tidied, nothing added),
   and the marking screen labels it "Her own answer". Where she left nothing the steps
   are THE TOOL'S, in her one-mark-per-step style, and say which of her pages they come
   from. Keyed on the normalised opening of the question text ONLY (an overlay may never
   key on what it writes). build.mjs fails if an entry matches no essay, and HOLDS any
   essay with no entry. One entry covers a question she posted twice (the CVS Lab Review
   and Practice Lab 1 share nine). */
export const norm = s => s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

export const SAQ_ANSWERS = [
  // ── 211012 · CVS Review: SAQ & MC (35 mk) ──
  {
    k: 'examine the figure above of the pulmonary and systemic circulations',
    hers: true,
    steps: [
      'Misconception 1: the pulmonary system does not "deliver oxygenated blood to the lungs" — it connects and delivers blood to and from the lungs FOR oxygenation.',
      'Misconception 2: the systemic circuit does not "drain deoxygenated blood from the lungs" — it delivers blood to and from the rest of the body for the purpose of cellular activity.',
      'Misconception 3: "the lung tissue gets oxygen from the pulmonary system" is wrong — the bronchial artery delivers oxygenated blood to the lung tissue and the bronchial vein returns the deoxygenated blood to the heart.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'go through the following answer to the question below describe the components of the heart s conduction system',
    hers: true,
    steps: [
      'Misconception 1: the SA and AV nodes are pacemakers, not neuromuscular junctions — self-excitatory, autogenic myocardial tissue generating the heart rhythm; the heart can beat on its own without nervous stimulation or brain involvement.',
      'Misconception 2: the electrical activity does not come from the medulla oblongata via nerves — it is generated by the SA and AV nodes themselves.',
      'Correct answer: the conduction system is the SA and AV nodes, Bundle of His, bundle branches and Purkinje fibres, plus the conductive myocardium; its point is to spread electrical activity through the heart muscle in a coordinated way, for correct and efficient contraction.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'describe the difference in normal bp mean in the arteries arterioles capillaries and venae cavae',
    hers: true,
    steps: [
      'Arteries = very high; arterioles = high; capillaries = gradually decrease but low overall; venae cavae = low.',
      'BP depends on the contraction force of the heart and the peripheral resistance: arteries receive blood directly from the heart, and pressure falls as blood passes through the capillary beds, after which the veins receive it.',
      'Arterial walls also offer the greatest resistance against the pumping force of the heart because of their thick tunica media.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'describe the role of the renin angiotensin aldosterone pathway and the ace inhibitors',
    hers: true,
    steps: [
      'RAAS is a powerful but slow renal response to LOW blood pressure.',
      'It stimulates the formation of angiotensin II — a powerful vasoconstrictor, so peripheral resistance rises.',
      'It stimulates fluid retention — ADH release (water retention) and aldosterone release (sodium, therefore fluid, retention) — so blood volume and stroke volume rise, and BP rises.',
      'ACE inhibitors block the conversion of angiotensin I to angiotensin II, so they prevent both the fall in vessel diameter (the PR rise) and the rise in blood volume (the SV rise).',
      'BP = SV × PR × HR: by acting on two of the three factors, ACE inhibitors are powerful antihypertensives.',
    ],
    src: 'her feedback comment on this question',
  },

  // ── 212709 · Heart Coverings & Structures (SAQ; no comments, so from her CVS 2 page + heart-coverings board) ──
  {
    k: 'what is the difference between the pectinate and trabecular muscles',
    hers: true,
    steps: [
      'Pectinate muscles ("like the teeth of a comb") are parallel muscle columns in the inner wall of both ATRIA — extra reinforcement and stretch; they act like an accordion, enlarging and reducing the size of the atria.',
      'Trabeculae carneae are muscular ridges projecting from and criss-crossing the inner walls of the VENTRICLES — they prevent suction inside the heart (as flat walls would allow), help anchor the AV valves and strengthen the wall.',
    ],
    src: 'her "Heart coverings & structures" discussion post',
  },
  {
    k: 'what is the difference between the aortic and pulmonary semilunar valves',
    hers: true,
    steps: [
      'Both are semilunar valves — three half-moon flaps that prevent backflow from the large arteries leaving the ventricles; their closure is the DUB (second heart sound).',
      'The pulmonary valve prevents backflow from the pulmonary artery into the RIGHT ventricle; the aortic valve prevents backflow from the aorta into the LEFT ventricle — and the coronary ostia sit just above the aortic valve flaps, which is how you tell them apart.',
    ],
    src: 'her CVS 2 learning page, "SAQ: semilunar valves"',
  },
  {
    k: 'what is the difference between the visceral and parietal pericardium',
    hers: true,
    steps: [
      'Visceral pericardium (= the epicardium) lies directly on the organ, covering the heart surface.',
      'Parietal pericardium is the outer serous layer, lining the fibrous pericardium; the pericardial cavity with its fluid lies between the two.',
    ],
    src: 'her feedback on the CVS Lab Review pericardium question',
  },
  {
    k: 'what is the difference between pericardium epicardium and endocardium',
    steps: [
      'Pericardium: the double-walled bag around the heart — a tough outer fibrous pericardium and a serous pericardium with parietal and visceral layers and pericardial fluid between them.',
      'Epicardium: the visceral layer of the serous pericardium — the outermost layer of the heart WALL, with a layer of fatty connective tissue between it and the myocardium.',
      'Endocardium: the smooth inner lining of the chambers and valves, continuous with the lining of the vessels (endocarditis = its inflammation, with valve complications).',
    ],
    src: 'her CVS 2 learning page, Task 1, and her heart-coverings post (Patton Fig 28-5)',
  },
  {
    k: 'what is the difference between t he tricuspid and mitral valve',
    hers: true,
    steps: [
      'The tricuspid valve (RIGHT side, between right atrium and right ventricle) has 3 delicate flaps.',
      'The mitral (bicuspid) valve (LEFT side, between left atrium and left ventricle) has 2 robust and large flaps — its chordae tendineae and flaps are far more robust than those on the right.',
    ],
    src: 'her CVS 2 learning page, "SAQ: AV valves"',
  },
  {
    k: 'what is the difference between t he semilunar and atrioventricular valves',
    hers: true,
    steps: [
      'AV valves separate an atrium from a ventricle on each side; they prevent backflow to the atria when the ventricles contract; their closure is the LUB (first heart sound); they open only to the ventricular side because chordae tendineae hold their flaps to the papillary muscles.',
      'Semilunar valves sit at the exits of the ventricles (pulmonary and aortic); three half-moon flaps prevent backflow from the great arteries; their closure is the DUB (second heart sound); no chordae — the cusps fill and seal like pockets.',
    ],
    src: 'her CVS 2 learning page, "SAQ: AV valves" and "SAQ: semilunar valves"',
  },
  {
    k: 'what are the papillary muscles and what is their function',
    hers: true,
    steps: [
      'Small muscles projecting from the ventricular wall that anchor the AV valves through the chordae tendineae (thread-like bands of fibrous tissue attached to the valve edges).',
      'When the ventricle contracts they contract too, holding the flaps shut so the valve can only open towards the ventricle — no backflow, no prolapse into the atrium.',
    ],
    src: 'her heart-coverings post and CVS 2 learning page',
  },
  {
    k: 'heart sounds can be heard when the semilunar and atrioventricular valves close',
    hers: true,
    steps: [
      'LUB (first heart sound) = closure of the atrioventricular valves (tricuspid and mitral) as the ventricles start to contract.',
      'DUB (second heart sound) = closure of the semilunar valves (aortic and pulmonary) as the ventricles relax.',
    ],
    src: 'her CVS 2 learning page SAQ answers',
  },
  {
    k: 'extra sounds are called murmurs what may cause heart murmurs',
    steps: [
      'A valve that does not close properly (incompetent/leaky) — blood regurgitates back where it came from and swishes.',
      'A valve that does not open properly (stenosis — stiff, narrowed flaps, e.g. after endocarditis) — blood is forced through a narrow opening turbulently.',
      'Either way, turbulent rather than smooth flow makes the extra sound; the result can be reduced cardiac output and an overworked, hypertrophied muscle.',
    ],
    src: 'her heart-coverings post ("valve stenosis, incompetent valves, regurgitation") and CVS 2 learning page',
  },

  // ── 211111 · CVS Lab Review (student-marked) — nine of these repeat in Practice Lab 1 ──
  {
    k: 'name all the arteries that arise from the arch of the aorta',
    hers: true,
    steps: [
      'The brachiocephalic trunk — supplying the right arm and the right side of the head.',
      'The left (common) carotid — supplying the left side of the head.',
      'The left subclavian — supplying the left arm. (The arch then continues as the descending aorta, supplying the lower body.)',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'name two missing arteries that arise from the arch of the aorta',
    hers: true,
    steps: [
      'The brachiocephalic trunk (innominate artery) — supplying the right arm and the right side of the head.',
      'The left subclavian — supplying the left arm.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'name four arteries that directly arise from the descending aorta and the organs they supply',
    hers: true,
    steps: [
      'Left and right renal arteries — the kidneys.',
      'The coeliac trunk — via the common hepatic artery to the liver, the splenic artery to the spleen, the left gastric artery to the stomach.',
      'The superior and inferior mesenteric arteries — the small and large intestine. (Also phrenic, suprarenal, gonadal — "there are more than 4!")',
      'It finally splits into the common iliac arteries that supply each leg.',
    ],
    src: 'her feedback comment and the labelled aorta diagram she posted on it',
  },
  {
    k: 'name the major blood vessels artery and vein in the neck',
    hers: true,
    steps: [
      'Artery: the common carotid arteries (splitting into internal and external carotids), with the vertebral arteries behind them.',
      'Vein: the jugular veins. (Brachiocephalic trunk and innominate artery are the same vessel.)',
    ],
    src: 'her feedback comment and the neck-arteries diagram she posted on it',
  },
  {
    k: 'name the major artery to the upper limb name the major artery to the lower limb',
    hers: true,
    steps: [
      'Arm — the subclavian artery, which continues as axillary → brachial → radial and ulnar (brachial and radial pulse sites).',
      'Leg — the femoral artery (the iliac is still up in the hip), continuing as popliteal → anterior and posterior tibial → dorsalis pedis (femoral, popliteal, posterior tibial and dorsalis pedis pulse sites).',
    ],
    src: 'her feedback comment and the limb-arteries diagram she posted on it',
  },
  {
    k: 'name four veins that directly empty into the inferior vena cava and the organs they drain',
    hers: true,
    steps: [
      'Common iliac veins — the legs and pelvis.',
      'Renal veins — the kidneys; suprarenal veins — the adrenal glands.',
      'Gonadal veins — the ovaries/testes.',
      'Hepatic veins — the liver (carrying everything the hepatic portal vein brought in).',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'name a ll the blood vessels that merge to form the hepatic portal vein',
    hers: true,
    steps: [
      'Superior mesenteric vein (small intestine, part of the colon) and splenic vein (spleen, with the inferior mesenteric vein from the large intestine joining it), plus the gastric veins from the stomach.',
      'The hepatic portal vein carries blood from the gut capillaries through the liver capillaries WITHOUT going through the heart first.',
      'That deoxygenated blood is full of absorbed nutrients that the liver must process (store, convert, detoxify) before they reach the general circulation.',
    ],
    src: 'her feedback comment and the portal-vein diagram she posted on it',
  },
  {
    k: 'use the histological images and diagrams provided on canvas to draw diagrams of an artery and a vein',
    hers: true,
    steps: [
      'Both walls have three layers: tunica intima (endothelium), tunica media (smooth muscle ± elastic fibres), tunica adventitia/externa (connective tissue).',
      'Artery: smaller round lumen, stiff appearance, THICK tunica media, clear internal (and external) elastic lamina, thin externa — it takes the pumping force of the heart and, in the arterioles, sets peripheral resistance.',
      'Vein: larger floppy lumen, THIN media, thick externa, elastic lamina not clear, valves — veins come after the capillary beds so the heart’s pumping force is not transferred to them; muscle and breathing push the blood.',
    ],
    src: 'her artery-vs-vein table on the CVS Review quiz and the labelled histology image she posted',
  },
  {
    k: 'the heart is located in a double walled bag made of connective tissue',
    hers: true,
    steps: [
      '1. Visceral = directly on the organ, covering the heart surface (the epicardium); parietal = the outer serous layer.',
      '2. The parietal layer is connected to the diaphragm (the phrenico-pericardial ligament).',
      '3. Pericardial fluid lies between the visceral and parietal SEROUS layers — the pericardial cavity.',
      '4. Together they prevent friction (the fluid) and the thick fibrous outer layer prevents overfilling by giving the heart a maximum size it can stretch to.',
      '5. "Serous" = it makes serum: a thin, watery, typically pale-yellow fluid.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'why can you feel a pulse in an artery but not a vein',
    hers: true,
    steps: [
      'The pulse is a wave of movement in the artery walls made by the pulsatile, "squirty" flow of blood from the heart.',
      'The wave is not strong enough to travel through the capillary beds to the veins — it is the muscular effort of the body (and breathing), not the heart’s pumping, that pushes blood through veins.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'what types of abnormalities can an ecg detect give two examples',
    hers: true,
    steps: [
      'Only anomalies caused by changes in the heart’s ELECTRICAL activity: conduction, rate and rhythm.',
      'Examples: rate — tachycardia (>100 b/min) or bradycardia (<60); rhythm — regular vs irregular, atrial or ventricular fibrillation; blocks and other conduction-system faults; type of myocardial infarction — STEMI (total coronary occlusion) vs NSTEMI (partial).',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'discuss the heart rate changes that occur would occur during the different ecg readings',
    hers: true,
    steps: [
      'Sitting, resting — around your resting heart rate.',
      'Supine, resting — lying down the heart does not have to pump against gravity up to the head, so it works less hard; rate can fall.',
      'Immediately on standing — the heart suddenly has to fight gravity: a sharp rise in rate to keep the head perfused, settling back to normal.',
      'Immediately after exercise, standing — still pumping hard and fast: the muscles must restore their energy stores and need extra oxygen for a while, so the rate returns to normal only slowly.',
    ],
    src: 'her feedback comment on this question',
  },

  // ── 211021 · Practice Lab 1 (the ones not shared with the Lab Review) ──
  {
    k: 'patient a had a myocardial infarction due to the total occlusion of the left anterior descending',
    hers: true,
    steps: [
      '1. From the left ventricle, via the aorta and the left coronary artery (through the coronary ostia just above the aortic valve).',
      '2. The anterior wall of the heart, the apex, and the septum — with the bundle branches of the conduction system.',
      '3. The atria contract normally but ventricular contraction is delayed and slow — myocardial cells themselves have to take over conduction — so the QRS widens; it can progress to complete heart block, where no impulses get from atria to ventricles: a medical emergency.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'what is the fibrous material on the outside of the heart called what is its function',
    hers: true,
    steps: [
      'The pericardium — actually two layers: a thick, obvious outer fibrous layer, and a thin layer that covers the heart surface.',
      'Together they prevent friction, thanks to the pericardial fluid, and the thick outer layer prevents overfilling by giving the heart a maximum size it can stretch to.',
    ],
    src: 'her feedback comment on this question',
  },

  // ── 211102 · Module 1 Formative ──
  {
    k: 'jo is admitted to hospital with a stab wound in the thigh',
    steps: [
      '1. Hypovolaemic shock — fluid (here blood) loss from traumatic injury.',
      '2. BP = SV × HR × PR: blood loss lowers blood volume and venous return, so the ventricle fills less and stroke volume falls — BP falls with it (a faster HR and vasoconstriction compensate only for a while).',
      '3.1 Low BP means low capillary hydrostatic pressure at the arterial end, so less fluid is filtered out; plasma proteins are still there so oncotic pressure now outweighs it and net movement is INTO the capillaries — the body pulls interstitial fluid back to refill the blood.',
      '3.2 Lymph is the ~10% of capillary filtrate the veins do not reabsorb; with far less filtered and more reabsorbed, less interstitial fluid forms, so lymph flow falls.',
    ],
    src: 'her Circulatory Shock page and her capillary-exchange comments on the CVS Review quiz',
  },
  {
    k: 'asthma medications used as relievers and preventers have different effects',
    hers: true,
    steps: [
      '1. The conduction zone = all the structures that bring air to the respiratory zone (where gas exchange happens — respiratory bronchioles and alveoli): nose, pharynx, larynx, trachea, bronchi and bronchioles up to the terminal bronchiole.',
      '2a. Reliever = bronchodilator: relaxes the smooth-muscle layer in the wall of the trachea, bronchi and bronchioles, widening them to improve airflow.',
      '2b. Preventer = corticosteroid: suppresses the over-active immune response (mast cells releasing histamine → leaky capillaries → inflammation) — an anti-inflammatory that reduces swelling of the epithelium and so widens the airways.',
    ],
    src: 'her feedback comment on this question',
  },

  // ── 211920 · Respiratory SAQ (20 mk) ──
  {
    k: 'diseases like copd and pneumonia affect different parts of the lungs',
    hers: true,
    steps: [
      'COPD → the conductive zone: nose, pharynx, trachea, bronchi, bronchioles — the parts bringing air to and from the respiratory zone and cleaning/conditioning it.',
      'It obstructs airflow through inflammation, mucus production and airway narrowing as the smooth muscle contracts.',
      'Ventilation becomes hard work, so accessory muscles are needed to create a big enough pressure gradient to move air in and out.',
      'Pneumonia → the respiratory zone: respiratory bronchioles and alveoli, where external respiration (gas exchange) happens.',
      'It fills the lungs with fluid and pus, increasing the diffusion distance — simple diffusion needs thin membranes to be efficient.',
      'So the blood cannot be oxygenated sufficiently (O₂ must move in) and CO₂ cannot be got out.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'breathing can influence the ph of the blood discuss the following statement',
    hers: true,
    steps: [
      'Hyperventilation (fast, deep): CO₂ is blown off faster than it is produced → less CO₂ in the blood → blood more alkaline → respiratory alkalosis.',
      'Hypoventilation (slow, shallow): less CO₂ blown out than produced → more CO₂ in the blood → blood more acidic → respiratory acidosis.',
      'But in METABOLIC alkalosis (kidney, GI causes — e.g. a lot of vomiting) slow, shallow breathing retains CO₂ to bring the pH DOWN: hypoventilation as compensation.',
      'And in METABOLIC acidosis (e.g. diabetic ketoacidosis) fast, deep breathing gets rid of CO₂ to bring the pH UP: hyperventilation as compensation.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'discuss the role of the accessory muscles in forced breathing',
    hers: true,
    steps: [
      'Accessory muscles are recruited when extra ventilation is needed — exercise, or disease.',
      'Forced inhalation: neck muscles (scalenes, sternocleidomastoid) and chest muscles (pectoralis) lift the ribs, sternum and collarbone higher, making the thoracic cavity even larger than normal for a greater pressure gradient.',
      'Forced exhalation: abdominal muscles (rectus abdominis, external and internal obliques) compress the abdominal organs and push the diaphragm higher, and the internal intercostals pull the ribs down and in — a thoracic cavity even smaller than normal, again for a greater pressure gradient.',
    ],
    src: 'her feedback comment on this question',
  },

  // ── 211010 · Respiratory Practice Test ──
  {
    k: 'discuss how the lung s self cleaning ability is affected by smoking',
    hers: true,
    steps: [
      'Self-cleaning (1.5): chemicals in smoke paralyse the cilia of the mucociliary escalator, so particles trapped in the mucus descend into the alveoli instead of being brought upwards.',
      'Gas exchange (1): the excess mucus and fluid produced in pneumonia covers the thin squamous respiratory epithelium, increasing the distance through which gases must diffuse.',
    ],
    src: 'her feedback comment on this question',
  },

  // ── 211144 · Resp: Basic Anatomy ──
  {
    k: 'find and describe at least one error in the labelling of the ai created summary',
    hers: true,
    steps: [
      'The label lines for the visceral and parietal pleura point at the intercostal muscles, not the membranes.',
      'The interpleural space could be labelled more accurately — the two pleural layers are clearly visible.',
      'The structure labelled "bronchiole" has cartilage in its wall, so it is a small bronchus — bronchioles have no cartilage.',
      'The structure labelled as a bronchiole in the alveolar picture is in fact an alveolus.',
    ],
    src: 'her feedback comment (and marked-up images) on this question',
  },

  // ── 211067 · Respiratory Pre-Lab ──
  {
    k: 'self mark define lung compliance',
    hers: true,
    steps: ['Lung compliance is a measure of the lung’s ability to stretch — elastin gives it that stretchy quality, important for inflation.'],
    src: 'her feedback comment on this question',
  },
  {
    k: 'self mark define pneumothorax atelectasis',
    hers: true,
    steps: [
      'Pneumothorax: air in the pleural cavity — the intrapleural pressure becomes 0 (no longer negative), so the lung collapses (fully recoils).',
      'Atelectasis: collapse of part of the lung, or failure to expand — pneumothorax is one of its causes.',
    ],
    src: 'her feedback comment on this question',
  },

  // ── 211070 · Practice Lab 2 ──
  {
    k: 'this is a micrograph of lung tissue choose four numbered parts',
    hers: true,
    steps: [
      '1–2: bronchus lumen, lined with ciliated pseudostratified columnar epithelium (the mucociliary escalator that cleans the air) and held open by hyaline cartilage so air flows freely.',
      '3–4: ciliated pseudostratified columnar epithelium — traps particles in mucus and beats them upwards, away from the alveoli; cuboidal epithelium of the bronchiole — secretes surfactant components (keeps bronchioles open) and protective proteins.',
      '5–7: alveolus with thin walls for external respiration; type 1 cells (squamous) form the thin respiratory membrane for diffusion; type 2 cells (cuboidal) make surfactant to lower surface tension so the walls do not cling together.',
      '8–9: red blood cells in the capillary bring CO₂ to the alveolus and collect O₂; alveolar sacs on the alveolar duct give the large surface area for efficient exchange. (Any four parts.)',
    ],
    src: 'her feedback comment on this question ("ANY 4"), her nine parts grouped',
  },

  // ── 211019 · Fluid, Electrolyte & Fluid Balance ──
  {
    k: 'explain why a kwashiorkor a condition caused by a diet deficient in protein',
    hers: true,
    steps: [
      'Low protein in the diet means low protein in the blood plasma.',
      'Plasma proteins (albumin) are what pull fluid back in, so oncotic pressure at the venous end of the capillaries falls → less reabsorption → fluid builds up in the interstitium: oedema, in the abdomen a distended belly.',
    ],
    src: 'her feedback comment on this question',
  },
  {
    k: 'explain the link between hypertension and edema',
    hers: true,
    steps: [
      'High blood pressure means high hydrostatic pressure at the arterial end of the capillaries, which forces more fluid out into the interstitium.',
      'That overwhelms the drainage system (venous reabsorption plus the lymphatics), so fluid accumulates in the tissues: oedema.',
    ],
    src: 'her feedback comment on this question',
  },
];
